plugins {
    id "net.neoforged.moddev" version "2.0.141"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
        }
    }
}

repositories {
    maven { url = "https://maven.shedaniel.me/" }
    mavenCentral()
}

dependencies {
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}
