modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="no_more_mod_whitelist"
version="${version}"
displayName="NoMoreMod-Whitelist"
authors="Aether_254"
description='''Overrides the mod and file information reported by ModWhiteList 2.0.0 with a configurable derived list.'''

[[mixins]]
config="no_more_mod_whitelist.mixins.json"

[[dependencies.no_more_mod_whitelist]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="CLIENT"

[[dependencies.no_more_mod_whitelist]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.no_more_mod_whitelist]]
modId="modwhitelist"
type="required"
versionRange="[1.21.1-2.0.0]"
ordering="AFTER"
side="CLIENT"

[[dependencies.no_more_mod_whitelist]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="CLIENT"
